<a href="https://colab.research.google.com/github/northpr/tensorflow-resources/blob/main/udemy_tensorflow_course/00_Getting_started.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import tensorflow as tf
print(tf.__version__)

2.8.2


In [ ]:
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [ ]:
scalar.ndim

0

In [ ]:
vector = tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [ ]:
vector.ndim

1

In [ ]:
matrix = tf.constant([[10,7],[5,2]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 5,  2]], dtype=int32)>

In [ ]:
matrix.ndim

2

In [ ]:
matrix_2 = tf.constant([[1,2],
                        [3,4],
                        [5,6]])
matrix_2[0]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([1, 2], dtype=int32)>

In [ ]:
tensor = tf.constant([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]],[[13,14,15],[16,17,18]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [ ]:
tensor.ndim

3

In [ ]:
changeable_tensor = tf.Variable([10,7])
unchageable_tensor = tf.constant([2,34])
changeable_tensor, unchageable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 2, 34], dtype=int32)>)

In [ ]:
# # Will error (requires the .assign() method)
# changeable_tensor[0] = 7
# changeable_tensor

TypeError: ignored

In [ ]:
changeable_tensor[0].assign(4)
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([4, 7], dtype=int32)>

## Create random tensors

In [ ]:
# Create random tensors
random_1 = tf.random.Generator.from_seed(42)
random_1 = random_1.normal(shape=(3,2))
random_2 = tf.random.Generator.from_seed(42)
random_2 = random_2.normal(shape=(3,2))

random_1, random_2, random_1==random_2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

In [ ]:
## Shuffle a tensor
not_shuffled = tf.constant([[10,7],
                            [3,4],
                           [2,5]])

tf.random.shuffle(not_shuffled)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 3,  4],
       [ 2,  5],
       [10,  7]], dtype=int32)>

In [ ]:
tf.random.shuffle(not_shuffled, seed=32)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 2,  5],
       [ 3,  4]], dtype=int32)>

## Make tensors of all ones

In [ ]:
tf.ones(shape=(3,2))

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[1., 1.],
       [1., 1.],
       [1., 1.]], dtype=float32)>

In [ ]:
tf.zeros(shape=(3,2))

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[0., 0.],
       [0., 0.],
       [0., 0.]], dtype=float32)>

## Turn Numpy into tensor

In [ ]:
import numpy as np
numpy = np.arange(1, 25, dtype=np.int32)
numpy

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [ ]:
a = tf.constant(numpy, shape=(2,4,3))
a

<tf.Tensor: shape=(2, 4, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18],
        [19, 20, 21],
        [22, 23, 24]]], dtype=int32)>

## Getting information from Tensors (shape, rank, size)

In [ ]:
rank_4_tensor = tf.zeros([2, 3, 4, 5])
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [ ]:
print(f'.Shape: {rank_4_tensor.shape},\nndim: {rank_4_tensor.ndim},\nsize: {tf.size(rank_4_tensor)}')

.Shape: (2, 3, 4, 5),
ndim: 4,
size: 120


In [ ]:
# Get various attributes of tensor
print("Datatype of every element:", rank_4_tensor.dtype)
print("Number of dimensions (rank):", rank_4_tensor.ndim)
print("Shape of tensor:", rank_4_tensor.shape)
print("Elements along axis 0 of tensor:", rank_4_tensor.shape[0])
print("Elements along last axis of tensor:", rank_4_tensor.shape[-1])
print("Total number of elements (2*3*4*5):", tf.size(rank_4_tensor).numpy()) # .numpy() converts to NumPy array

Datatype of every element: <dtype: 'float32'>
Number of dimensions (rank): 4
Shape of tensor: (2, 3, 4, 5)
Elements along axis 0 of tensor: 2
Elements along last axis of tensor: 5
Total number of elements (2*3*4*5): 120


In [ ]:
rank_2_tensor = tf.Variable([[10, 7],
                             [2, 3]])
rank_2_tensor

<tf.Variable 'Variable:0' shape=(2, 2) dtype=int32, numpy=
array([[10,  7],
       [ 2,  3]], dtype=int32)>

### expand_dims

In [ ]:
tf.expand_dims(rank_2_tensor,axis=1)

<tf.Tensor: shape=(2, 1, 2), dtype=int32, numpy=
array([[[10,  7]],

       [[ 2,  3]]], dtype=int32)>

## Basic operations

In [ ]:
tensor = tf.constant([[10, 7],[3, 4]])
tensor = tensor + 10

tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]], dtype=int32)>

In [ ]:
tensor_variable = tf.Variable([[2,5],[1,3]])
tensor_variable = tensor + 10

tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]], dtype=int32)>

In [ ]:
tf.multiply(tensor, 2)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 2,  4],
       [ 6, 10]], dtype=int32)>

### Matrix multiplication

In [ ]:
# Matrix multiplication
tensor = tf.constant([[1,2],[3,5]])
tf.matmul(tensor, tensor)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 7, 12],
       [18, 31]], dtype=int32)>

In [ ]:
# Create (3, 2) tensor
X = tf.constant([[1, 2],
                 [3, 4],
                 [5, 6]])

# Create another (3, 2) tensor
Y = tf.constant([[7, 8],
                 [9, 10],
                 [11, 12]])
X, Y

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>, <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 7,  8],
        [ 9, 10],
        [11, 12]], dtype=int32)>)

In [ ]:
# tf.reshape

X = tf.reshape(X, shape=(2,3))

In [ ]:
tf.matmul(X, Y)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 58,  64],
       [139, 154]], dtype=int32)>

In [ ]:
tf.transpose(X)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 4],
       [2, 5],
       [3, 6]], dtype=int32)>

### Dot product

In [ ]:
X, Y

(<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 2, 3],
        [4, 5, 6]], dtype=int32)>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 7,  8],
        [ 9, 10],
        [11, 12]], dtype=int32)>)

In [ ]:
tf.tensordot(X,Y, axes=1)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 58,  64],
       [139, 154]], dtype=int32)>

In [ ]:
tf.matmul(X, Y)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 58,  64],
       [139, 154]], dtype=int32)>

In [ ]:
tf.reshape(X, shape=(6,1))

<tf.Tensor: shape=(6, 1), dtype=int32, numpy=
array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]], dtype=int32)>

## Chaning te data type of a tensor

In [ ]:
# Create a new tensor with default datatype (float32)
B = tf.constant([1.2,3.5])

# Create a new tensor with default datatype (float32)
C = tf.constant([5,4])

B,C

(<tf.Tensor: shape=(2,), dtype=float32, numpy=array([1.2, 3.5], dtype=float32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([5, 4], dtype=int32)>)

In [ ]:
# Change from float32 to float16 (reduced precision)
B = tf.cast(B, dtype='float16')
B

<tf.Tensor: shape=(2,), dtype=float16, numpy=array([1.2, 3.5], dtype=float16)>

## Getting the absolute error

In [ ]:
D = tf.constant([-7,-10])
tf.abs(D)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 7, 10], dtype=int32)>

## Finding the min, max, mean, sum

In [ ]:
E = tf.constant(np.random.randint(low=0, high=100, size=50))
E

<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([16, 64, 84, 62, 86, 15, 94, 41, 80, 51, 61, 39, 49, 20, 58, 86, 66,
       83, 64, 82, 24, 60, 51, 19, 72, 57, 93, 39, 38, 20, 99, 72, 38, 34,
       71, 39, 56, 69, 49,  8, 18, 43, 80, 87, 91,  9, 31, 63, 76, 92])>

### 1-D

In [ ]:
tf.reduce_min(E)

<tf.Tensor: shape=(), dtype=int64, numpy=8>

In [ ]:
tf.reduce_mean(E)

<tf.Tensor: shape=(), dtype=int64, numpy=55>

In [ ]:
tf.reduce_max(E)

<tf.Tensor: shape=(), dtype=int64, numpy=99>

In [ ]:
tf.reduce_sum(E)

<tf.Tensor: shape=(), dtype=int64, numpy=2799>

### 2-D

In [ ]:
E = tf.constant(np.random.randint(low=0, high=100, size=50))
E = tf.reshape(E, shape=(10,5))
E = tf.cast(E, dtype='float64')
E

<tf.Tensor: shape=(10, 5), dtype=float64, numpy=
array([[49., 19., 40., 41., 25.],
       [61., 64., 82., 80., 40.],
       [32., 67., 56., 61., 15.],
       [19., 57., 93., 14., 14.],
       [38.,  2., 87., 45., 45.],
       [14., 73., 95., 33., 21.],
       [55., 79., 49., 43., 73.],
       [59., 23., 65., 78., 14.],
       [25., 31., 61., 79., 55.],
       [82., 43., 24., 27., 27.]])>

In [ ]:
e_axis0 = tf.reduce_mean(E, axis=0)
e_axis1 = tf.reduce_mean(E, axis=1)

e_axis0, e_axis1

(<tf.Tensor: shape=(5,), dtype=float64, numpy=array([43.4, 45.8, 65.2, 50.1, 32.9])>,
 <tf.Tensor: shape=(10,), dtype=float64, numpy=array([34.8, 65.4, 46.2, 39.4, 43.4, 47.2, 59.8, 47.8, 50.2, 40.6])>)

### 3-D

In [ ]:
E = tf.constant(np.random.randint(low=0, high=100, size=60))
E = tf.cast(E, dtype="float64")
E = tf.reshape(E, shape=(3,5,4))
E

<tf.Tensor: shape=(3, 5, 4), dtype=float64, numpy=
array([[[10., 69., 16., 73.],
        [73., 61., 12., 75.],
        [72., 28., 40.,  0.],
        [73., 32., 43., 29.],
        [ 4., 62., 35., 78.]],

       [[20., 52.,  7., 16.],
        [99., 12., 99., 59.],
        [47., 36., 15.,  8.],
        [10., 80., 45., 74.],
        [24., 30.,  1.,  7.]],

       [[35., 11., 87., 13.],
        [ 7., 71., 55., 99.],
        [96., 57., 21., 90.],
        [78., 26.,  8., 87.],
        [66., 13., 84., 47.]]])>

In [ ]:
E_axis0 = tf.reduce_mean(E, axis=0) # (18+11+22)/3
E_axis1 = tf.reduce_mean(E, axis=1) # ()
E_axis2 = tf.reduce_mean(E, axis=2)

E_axis0, E_axis1, E_axis2

(<tf.Tensor: shape=(5, 4), dtype=float64, numpy=
 array([[21.66666667, 44.        , 36.66666667, 34.        ],
        [59.66666667, 48.        , 55.33333333, 77.66666667],
        [71.66666667, 40.33333333, 25.33333333, 32.66666667],
        [53.66666667, 46.        , 32.        , 63.33333333],
        [31.33333333, 35.        , 40.        , 44.        ]])>,
 <tf.Tensor: shape=(3, 4), dtype=float64, numpy=
 array([[46.4, 50.4, 29.2, 51. ],
        [40. , 42. , 33.4, 32.8],
        [56.4, 35.6, 51. , 67.2]])>,
 <tf.Tensor: shape=(3, 5), dtype=float64, numpy=
 array([[42.  , 55.25, 35.  , 44.25, 44.75],
        [23.75, 67.25, 26.5 , 52.25, 15.5 ],
        [36.5 , 58.  , 66.  , 49.75, 52.5 ]])>)

## Finding the positional maximum and minimum


In [ ]:
F = tf.constant(np.random.random(50))
F

<tf.Tensor: shape=(50,), dtype=float64, numpy=
array([0.16694846, 0.11246291, 0.2157042 , 0.85351103, 0.45343434,
       0.44238408, 0.68007727, 0.13519493, 0.80283949, 0.79213434,
       0.23541756, 0.41072797, 0.66816796, 0.42159491, 0.29797587,
       0.43931116, 0.7184465 , 0.60154204, 0.16094442, 0.75917822,
       0.2723495 , 0.34242086, 0.81204615, 0.6691134 , 0.86787867,
       0.89318645, 0.15617942, 0.16567609, 0.47325248, 0.53754929,
       0.9099251 , 0.29823386, 0.75767156, 0.1261189 , 0.37346231,
       0.97969197, 0.53447504, 0.57946265, 0.39148165, 0.68626431,
       0.62799923, 0.52195167, 0.05014026, 0.21812293, 0.59667739,
       0.95262214, 0.20146776, 0.81030017, 0.67317155, 0.25511877])>

In [ ]:
tf.argmax(F)

<tf.Tensor: shape=(), dtype=int64, numpy=35>

In [ ]:
F = tf.reshape(F, shape=(10,5))
F

<tf.Tensor: shape=(10, 5), dtype=float64, numpy=
array([[0.16694846, 0.11246291, 0.2157042 , 0.85351103, 0.45343434],
       [0.44238408, 0.68007727, 0.13519493, 0.80283949, 0.79213434],
       [0.23541756, 0.41072797, 0.66816796, 0.42159491, 0.29797587],
       [0.43931116, 0.7184465 , 0.60154204, 0.16094442, 0.75917822],
       [0.2723495 , 0.34242086, 0.81204615, 0.6691134 , 0.86787867],
       [0.89318645, 0.15617942, 0.16567609, 0.47325248, 0.53754929],
       [0.9099251 , 0.29823386, 0.75767156, 0.1261189 , 0.37346231],
       [0.97969197, 0.53447504, 0.57946265, 0.39148165, 0.68626431],
       [0.62799923, 0.52195167, 0.05014026, 0.21812293, 0.59667739],
       [0.95262214, 0.20146776, 0.81030017, 0.67317155, 0.25511877]])>

In [ ]:
tf.argmax(F, axis=0), tf.argmax(F, axis=1)

(<tf.Tensor: shape=(5,), dtype=int64, numpy=array([7, 3, 4, 0, 4])>,
 <tf.Tensor: shape=(10,), dtype=int64, numpy=array([3, 3, 2, 4, 4, 0, 0, 0, 0, 0])>)

In [ ]:
tf.argmin(F, axis=0), tf.argmin(F, axis=1)

(<tf.Tensor: shape=(5,), dtype=int64, numpy=array([0, 0, 8, 6, 9])>,
 <tf.Tensor: shape=(10,), dtype=int64, numpy=array([1, 2, 0, 3, 0, 1, 3, 3, 2, 1])>)

In [ ]:
tf.argmax(F).numpy()

array([7, 3, 4, 0, 4])

In [ ]:
# Find the maximum element of position F
print(f"The maximum of F is at position {tf.argmax(F,axis=0).numpy()}")
print(f"The maximum value of F is: {tf.reduce_max(F,axis=0)}")

The maximum of F is at position [7 3 4 0 4]
The maximum value of F is: [0.97969197 0.7184465  0.81204615 0.85351103 0.86787867]


In [ ]:
tf.reshape(F, shape=(1,50))

<tf.Tensor: shape=(1, 50), dtype=float64, numpy=
array([[0.16694846, 0.11246291, 0.2157042 , 0.85351103, 0.45343434,
        0.44238408, 0.68007727, 0.13519493, 0.80283949, 0.79213434,
        0.23541756, 0.41072797, 0.66816796, 0.42159491, 0.29797587,
        0.43931116, 0.7184465 , 0.60154204, 0.16094442, 0.75917822,
        0.2723495 , 0.34242086, 0.81204615, 0.6691134 , 0.86787867,
        0.89318645, 0.15617942, 0.16567609, 0.47325248, 0.53754929,
        0.9099251 , 0.29823386, 0.75767156, 0.1261189 , 0.37346231,
        0.97969197, 0.53447504, 0.57946265, 0.39148165, 0.68626431,
        0.62799923, 0.52195167, 0.05014026, 0.21812293, 0.59667739,
        0.95262214, 0.20146776, 0.81030017, 0.67317155, 0.25511877]])>

## Squeezing a tensor

In [ ]:
G = tf.constant(np.random.randint(low=0, high=100, size=50), shape=(1,1,1,1,50))
G

<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=int64, numpy=
array([[[[[98, 20, 79, 39, 39, 31, 75, 40, 34, 48,  2, 49, 56, 56, 90,
           66, 36, 90, 32, 44, 90, 49, 47,  8, 81, 92, 37, 88, 92, 58,
           32,  3, 99, 15, 47, 23, 87, 22, 61, 12, 46, 22, 99, 49, 63,
           39, 33, 32, 27, 48]]]]])>

In [ ]:
# remove all dimension to 1
G_squeezed = tf.squeeze(G)
G_squeezed, G_squeezed.shape

(<tf.Tensor: shape=(50,), dtype=int64, numpy=
 array([98, 20, 79, 39, 39, 31, 75, 40, 34, 48,  2, 49, 56, 56, 90, 66, 36,
        90, 32, 44, 90, 49, 47,  8, 81, 92, 37, 88, 92, 58, 32,  3, 99, 15,
        47, 23, 87, 22, 61, 12, 46, 22, 99, 49, 63, 39, 33, 32, 27, 48])>,
 TensorShape([50]))

In [ ]:
G = tf.constant(np.random.randint(low=0, high=100, size=50), shape=(1,1,1,1,50))
G = tf.reshape(G, -1)
G, G.shape 

(<tf.Tensor: shape=(50,), dtype=int64, numpy=
 array([60, 22, 60, 93, 54, 79, 70, 65, 89, 25, 42, 78, 82, 28, 28, 12, 97,
        33, 77, 55, 51, 86, 69,  5, 96,  5, 86, 42, 51, 27, 74, 33, 41, 88,
        95, 14, 38, 24, 93, 23, 41, 48, 21, 95,  9, 90, 31, 68,  2,  7])>,
 TensorShape([50]))

## One-hot encoding

In [ ]:
some_list = [2,3,1,2]
tf.one_hot(some_list, depth=4)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]], dtype=float32)>

In [ ]:
tf.one_hot(some_list, depth=4, on_value="we're live!", off_value="offine")

<tf.Tensor: shape=(4, 4), dtype=string, numpy=
array([[b'offine', b'offine', b"we're live!", b'offine'],
       [b'offine', b'offine', b'offine', b"we're live!"],
       [b'offine', b"we're live!", b'offine', b'offine'],
       [b'offine', b'offine', b"we're live!", b'offine']], dtype=object)>

## Square root

In [ ]:
H = tf.constant(np.arange(1,10))
H

<tf.Tensor: shape=(9,), dtype=int64, numpy=array([1, 2, 3, 4, 5, 6, 7, 8, 9])>

In [ ]:
tf.square(H)


<tf.Tensor: shape=(9,), dtype=int64, numpy=array([ 1,  4,  9, 16, 25, 36, 49, 64, 81])>

In [ ]:
H = tf.cast(H, dtype="float64")
tf.sqrt(H)

<tf.Tensor: shape=(9,), dtype=float64, numpy=
array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        ])>

# Exercise


In [ ]:
# 1. Create a vector, scalar, matrix
vector = tf.constant([1])
scalar = tf.constant([1,2])
matrix = tf.constant([[1,2],[3,4]])

vector, scalar, matrix

(<tf.Tensor: shape=(1,), dtype=int32, numpy=array([1], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([1, 2], dtype=int32)>,
 <tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4]], dtype=int32)>)

In [ ]:
# 2. Find shape, rank, size
vector.shape, scalar.ndim, tf.size(matrix)

(TensorShape([1]), 1, <tf.Tensor: shape=(), dtype=int32, numpy=4>)

In [ ]:
vector.ndim, scalar.ndim, matrix.ndim

(1, 1, 2)

In [ ]:
tf.size(vector), tf.size(scalar), tf.size(matrix)

(<tf.Tensor: shape=(), dtype=int32, numpy=1>,
 <tf.Tensor: shape=(), dtype=int32, numpy=2>,
 <tf.Tensor: shape=(), dtype=int32, numpy=4>)

In [ ]:
# 3. Create two tensors containing random value between 0,1 with shape [5,300]
a = tf.constant(np.random.rand(5,300))
a, a.shape

(<tf.Tensor: shape=(5, 300), dtype=float64, numpy=
 array([[0.52856741, 0.60974023, 0.7038834 , ..., 0.81912485, 0.21029401,
         0.99342345],
        [0.67176742, 0.93997237, 0.04780383, ..., 0.99779281, 0.3489504 ,
         0.95077694],
        [0.60213919, 0.87600895, 0.88416478, ..., 0.3357351 , 0.83128303,
         0.19538304],
        [0.50189335, 0.75121687, 0.95135167, ..., 0.71857672, 0.88669128,
         0.7536697 ],
        [0.93582634, 0.92968822, 0.558018  , ..., 0.14722546, 0.31735673,
         0.45383115]])>, TensorShape([5, 300]))

In [ ]:
# 6. Create a tensor with random values between 0 and 1 with shape [224,224,3]
z = tf.constant(np.random.rand(224,224,3))
z[0:10]

<tf.Tensor: shape=(10, 224, 3), dtype=float64, numpy=
array([[[0.32169825, 0.86773647, 0.28392285],
        [0.37040961, 0.48648149, 0.9093998 ],
        [0.44660866, 0.40307768, 0.1288615 ],
        ...,
        [0.03466701, 0.20051564, 0.60016472],
        [0.99441051, 0.81157415, 0.22896624],
        [0.55314549, 0.52558598, 0.95991399]],

       [[0.95787374, 0.14887509, 0.31825795],
        [0.72141881, 0.59207271, 0.01200287],
        [0.71373551, 0.77024249, 0.37450545],
        ...,
        [0.20773759, 0.76625002, 0.70980482],
        [0.78102957, 0.4086841 , 0.35169886],
        [0.11747313, 0.42512098, 0.71125958]],

       [[0.71132483, 0.13434274, 0.63691545],
        [0.81897707, 0.74463082, 0.01246067],
        [0.70283225, 0.55956801, 0.50671113],
        ...,
        [0.74272298, 0.24938272, 0.45463357],
        [0.88607449, 0.40895892, 0.87491911],
        [0.80287462, 0.70238652, 0.44410349]],

       ...,

       [[0.21540329, 0.43667639, 0.73742811],
        [0.679

In [ ]:
tf.argmax(z, axis=1)

<tf.Tensor: shape=(224, 3), dtype=int64, numpy=
array([[222,  88,  57],
       [ 16, 121, 142],
       [150, 106,  97],
       [159, 142, 203],
       [137, 217,  50],
       [ 55,  47,  53],
       [ 70, 144,  60],
       [ 11, 220, 146],
       [127, 188, 105],
       [168,  77, 190],
       [ 22, 204,  81],
       [115,   7,  89],
       [  3, 131, 104],
       [216, 214,  67],
       [200, 164, 145],
       [ 59, 164,  26],
       [138,  13, 128],
       [187,  53,  31],
       [179, 130,  98],
       [213,  37,  25],
       [ 51,  56, 181],
       [213, 215,  52],
       [ 79,  40,  73],
       [202,  31, 123],
       [121,  43, 116],
       [ 61, 159, 223],
       [ 47,  55,  24],
       [213,  34, 222],
       [181,  18,  62],
       [174,  83,   2],
       [114,  18,  47],
       [ 60,  61,  97],
       [ 25,  85,  50],
       [134, 111,  50],
       [171, 194,   1],
       [105, 149,  92],
       [ 48,  13, 148],
       [222,   2,  18],
       [211,  86, 196],
       [ 57, 181

In [ ]:
# 8. Created a tensor with random value of shape [1, 224, 224, 3]
a = tf.constant(np.random.randint(0, 100, 150528), shape=(1,224,224,3))
tf.reshape(a, shape=(224,224,3))

<tf.Tensor: shape=(224, 224, 3), dtype=int64, numpy=
array([[[18, 12, 10],
        [31, 31, 10],
        [29, 76, 67],
        ...,
        [69, 56, 69],
        [86, 30, 45],
        [83, 53, 64]],

       [[18, 21,  1],
        [48, 59, 80],
        [ 0, 72, 49],
        ...,
        [61, 27,  7],
        [79, 90, 61],
        [60, 50, 68]],

       [[18, 73, 39],
        [17, 98, 11],
        [74, 73, 39],
        ...,
        [77, 65,  2],
        [33, 96, 12],
        [ 8,  1, 79]],

       ...,

       [[53,  1, 47],
        [18, 77,  1],
        [94, 57, 67],
        ...,
        [40, 86, 45],
        [39, 15, 78],
        [35, 81,  4]],

       [[68,  1, 93],
        [ 4, 30, 29],
        [29, 53, 45],
        ...,
        [ 3, 55, 96],
        [77, 30, 84],
        [46, 63, 17]],

       [[24, 33, 38],
        [86, 30, 91],
        [47, 34,  2],
        ...,
        [57, 14, 51],
        [38, 94, 76],
        [38, 35, 83]]])>

In [ ]:
squeeze_test = tf.constant([[[1,2],[3,4]],
             [[5,6],[7,8]]])

tf.expand_dims(squeeze_test, -1)

<tf.Tensor: shape=(2, 2, 2, 1), dtype=int32, numpy=
array([[[[1],
         [2]],

        [[3],
         [4]]],


       [[[5],
         [6]],

        [[7],
         [8]]]], dtype=int32)>